# This workflow builds the Framework.All.sln and runs all tests for the solution
name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Framework-All.sln

    - name: Build solution
      run: dotnet build Framework-All.sln --configuration Release --no-restore

    - name: Run tests for DavidBerry.Framework
      run: >
        dotnet test DavidBerry.Framework/DavidBerry.Framework.Tests/DavidBerry.Framework.Tests.csproj \
          --configuration Release \
          --no-build \
          --logger "trx;LogFileName=DavidBerry.Framework.Tests.trx" \
          --results-directory TestResults/Framework \
          --collect:"XPlat Code Coverage" \
          /p:CollectCoverage=true \
          /p:CoverletOutput=TestResults/coverage/ \
          /p:CoverletOutputFormat=cobertura

    - name: Run tests for DavidBerry.Framework.ApiUtil
      run: >
        dotnet test DavidBerry.Framework.ApiUtil/DavidBerry.Framework.ApiUtil.Tests/DavidBerry.Framework.ApiUtil.Tests.csproj \
          --configuration Release \
          --no-build \
          --logger "trx;LogFileName=DavidBerry.Framework.ApiUtil.Tests.trx" \
          --results-directory TestResults/ApiUtil \
          --collect:"XPlat Code Coverage" \
          /p:CollectCoverage=true \
          /p:CoverletOutput=TestResults/coverage/ \
          /p:CoverletOutputFormat=cobertura          

    - name: Run tests for DavidBerry.Framework.Spatial
      run: >
        dotnet test DavidBerry.Framework.Spatial/DavidBerry.Framework.Spatial.Tests/DavidBerry.Framework.Spatial.Tests.csproj \
          --configuration Release \
          --no-build \
          --logger "trx;LogFileName=DavidBerry.Framework.Spatial.Tests.trx" \
          --results-directory TestResults/Spatial \
          --collect:"XPlat Code Coverage" \
          /p:CollectCoverage=true \
          /p:CoverletOutput=TestResults/coverage/ \
          /p:CoverletOutputFormat=cobertura

    - name: Upload test results artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/**.trx

    - name: Upload code coverage report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: TestResults/coverage/**/coverage.cobertura.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: TestResults/*.trx

    - name: Publish code coverage summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: TestResults/coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        output: both
